namespace SecondShiftAutoCare.Api.Entities;

public sealed class ServiceIntakeQuestion { public Guid Id { get; set; } public string ServiceType { get; set; }=string.Empty; public string QuestionText { get; set; }=string.Empty; public string? HelpText { get; set; } public string AnswerType { get; set; }=string.Empty; public string? OptionsJson { get; set; } public bool IsRequired { get; set; } public int SortOrder { get; set; } public bool IsActive { get; set; }=true; public ICollection<ServiceIntakeAnswer> Answers { get; set; }=[]; }
public sealed class ServiceIntakeAnswer { public Guid Id { get; set; } public Guid ServiceRequestId { get; set; } public ServiceRequest ServiceRequest { get; set; }=null!; public Guid? QuestionId { get; set; } public ServiceIntakeQuestion? Question { get; set; } public string QuestionText { get; set; }=string.Empty; public string? AnswerText { get; set; } public DateTime CreatedUtc { get; set; } }
public sealed class ChecklistTemplate { public Guid Id { get; set; } public string ServiceType { get; set; }=string.Empty; public string Name { get; set; }=string.Empty; public bool IsActive { get; set; }=true; public int SortOrder { get; set; } public ICollection<ChecklistTemplateItem> Items { get; set; }=[]; }
public sealed class ChecklistTemplateItem { public Guid Id { get; set; } public Guid ChecklistTemplateId { get; set; } public ChecklistTemplate ChecklistTemplate { get; set; }=null!; public string Text { get; set; }=string.Empty; public int SortOrder { get; set; } public bool IsRequired { get; set; } }
public sealed class JobChecklistItem { public Guid Id { get; set; } public Guid ServiceRequestId { get; set; } public ServiceRequest ServiceRequest { get; set; }=null!; public string Text { get; set; }=string.Empty; public bool IsCompleted { get; set; } public DateTime? CompletedUtc { get; set; } public int SortOrder { get; set; } public bool IsCustom { get; set; } public DateTime CreatedUtc { get; set; } public DateTime UpdatedUtc { get; set; } }
public sealed class Payment { public Guid Id { get; set; } public Guid ServiceRequestId { get; set; } public ServiceRequest ServiceRequest { get; set; }=null!; public string PaymentStatus { get; set; }=string.Empty; public string? PaymentMethod { get; set; } public decimal? AmountDue { get; set; } public decimal? AmountPaid { get; set; } public DateTime? PaidUtc { get; set; } public string? Notes { get; set; } public DateTime CreatedUtc { get; set; } public DateTime UpdatedUtc { get; set; } }
public sealed class JobRiskAssessment { public Guid Id { get; set; } public Guid ServiceRequestId { get; set; } public ServiceRequest ServiceRequest { get; set; }=null!; public bool RustConcern { get; set; } public bool RequiresLift { get; set; } public bool CustomerSuppliedParts { get; set; } public bool KnownDifficultVehicle { get; set; } public decimal? EstimatedHours { get; set; } public bool SafetyCritical { get; set; } public bool NeedsAlignment { get; set; } public bool NeedsTow { get; set; } public bool MobileWorkConcern { get; set; } public int RiskScore { get; set; } public string Recommendation { get; set; }=string.Empty; public string? Notes { get; set; } public DateTime CreatedUtc { get; set; } public DateTime UpdatedUtc { get; set; } }
