CREATE TABLE ServiceRequests (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    CustomerName NVARCHAR(100) NOT NULL,
    Phone NVARCHAR(30) NOT NULL,
    Email NVARCHAR(150) NULL,

    VehicleYear INT NOT NULL,
    VehicleMake NVARCHAR(75) NOT NULL,
    VehicleModel NVARCHAR(75) NOT NULL,
    Mileage INT NULL,

    ServiceType NVARCHAR(75) NOT NULL,
    Symptoms NVARCHAR(2000) NOT NULL,
    PreferredAvailability NVARCHAR(500) NULL,

    Status NVARCHAR(50) NOT NULL DEFAULT 'New',

    EstimateLow DECIMAL(10,2) NULL,
    EstimateHigh DECIMAL(10,2) NULL,
    PartsNeeded NVARCHAR(1000) NULL,
    InternalNotes NVARCHAR(2000) NULL,

    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
