using Microsoft.EntityFrameworkCore;
using SecondShiftAutoCare.Api.Data;
using SecondShiftAutoCare.Api.Entities;
using SecondShiftAutoCare.Shared.Models;

namespace SecondShiftAutoCare.Api;

public sealed class ServiceRequestRepository(ServiceRequestDbContext dbContext)
{
    public async Task<ServiceRequestDto> CreateAsync(ServiceRequestDto request)
    {
        var now = DateTime.UtcNow;
        var customer = new Customer { Id = Guid.NewGuid(), Name = request.CustomerName.Trim(), Phone = request.Phone.Trim(), Email = TrimOrNull(request.Email), CreatedUtc = now, UpdatedUtc = now };
        var vehicle = new Vehicle { Id = Guid.NewGuid(), CustomerId = customer.Id, Year = request.VehicleYear!.Value, Make = request.VehicleMake.Trim(), Model = request.VehicleModel.Trim(), Mileage = request.Mileage, CreatedUtc = now, UpdatedUtc = now };
        var serviceRequest = new ServiceRequest { Id = request.Id ?? Guid.NewGuid(), CustomerId = customer.Id, VehicleId = vehicle.Id, ServiceType = request.ServiceType.Trim(), ServiceSpecificAnswers = TrimOrNull(request.ServiceSpecificAnswers), Symptoms = TrimOrNull(request.Symptoms), Notes = null, PreferredAvailability = TrimOrNull(request.PreferredAvailability), UrgencyLevel = request.UrgencyLevel, IsVehicleDrivable = TrimOrNull(request.IsVehicleDrivable), VehicleLocation = TrimOrNull(request.VehicleLocation), ConsentAccepted = request.ConsentAccepted, WantsPhotoUploadLater = request.WantsPhotoUploadLater, Status = ServiceRequestStatuses.New, PublicStatusToken = NewToken(), QuoteApprovalToken = NewToken(), CreatedUtc = now, UpdatedUtc = now };
        var quote = new Quote { Id = Guid.NewGuid(), ServiceRequestId = serviceRequest.Id, CustomerApprovalStatus = ServiceRequestApprovalStatuses.Pending, CreatedUtc = now, UpdatedUtc = now };
        dbContext.AddRange(customer, vehicle, serviceRequest, quote);
        await AddIntakeAnswersAsync(serviceRequest, request.IntakeAnswers, now);
        await AddChecklistFromTemplateAsync(serviceRequest, now);
        await dbContext.SaveChangesAsync();
        serviceRequest.Customer = customer; serviceRequest.Vehicle = vehicle; serviceRequest.Quote = quote;
        return ToDto(serviceRequest);
    }

    public async Task<IReadOnlyList<ServiceRequestDto>> GetAllAsync(ServiceRequestQuery? query = null)
    {
        var q = dbContext.ServiceRequests.AsNoTracking().Include(x=>x.Customer).Include(x=>x.Vehicle).Include(x=>x.Quote).Include(x=>x.Payment).AsQueryable();
        query ??= new();
        if (!query.IncludeArchived) q = q.Where(x=>!x.IsArchived);
        if (!string.IsNullOrWhiteSpace(query.Status)) q = q.Where(x=>x.Status==query.Status);
        if (!string.IsNullOrWhiteSpace(query.ServiceType)) q = q.Where(x=>x.ServiceType.Contains(query.ServiceType));
        if (!string.IsNullOrWhiteSpace(query.PaymentStatus)) q = q.Where(x=>x.Payment != null && x.Payment.PaymentStatus==query.PaymentStatus);
        if (query.FromDate is not null) q = q.Where(x=>x.CreatedUtc >= query.FromDate);
        if (query.ToDate is not null) q = q.Where(x=>x.CreatedUtc <= query.ToDate);
        var now = DateTime.UtcNow; var today = now.Date;
        q = query.ScheduledFilter switch { "Unscheduled" => q.Where(x=>x.ScheduledStartUtc==null), "Today" => q.Where(x=>x.ScheduledStartUtc>=today && x.ScheduledStartUtc<today.AddDays(1)), "Next7Days" => q.Where(x=>x.ScheduledStartUtc>=now && x.ScheduledStartUtc<now.AddDays(7)), "Weekend" => q.Where(x=>x.ScheduledStartUtc!=null && ((int)x.ScheduledStartUtc.Value.DayOfWeek==0 || (int)x.ScheduledStartUtc.Value.DayOfWeek==6)), _=>q };
        if (!string.IsNullOrWhiteSpace(query.Search)) { var s=query.Search.Trim(); q=q.Where(x=>x.Customer.Name.Contains(s)||x.Customer.Phone.Contains(s)||(x.Customer.Email!=null&&x.Customer.Email.Contains(s))||x.Vehicle.Make.Contains(s)||x.Vehicle.Model.Contains(s)||x.Vehicle.Year.ToString().Contains(s)||x.ServiceType.Contains(s)||x.Status.Contains(s)); }
        q = query.Sort switch { "oldest" => q.OrderBy(x=>x.CreatedUtc), "scheduled" => q.OrderBy(x=>x.ScheduledStartUtc ?? DateTime.MaxValue), "scheduled_desc" => q.OrderByDescending(x=>x.ScheduledStartUtc), _ => q.OrderByDescending(x=>x.CreatedUtc) };
        return await q.Select(x=>ToDto(x)).ToListAsync();
    }
    public async Task<ServiceRequestDto?> GetByIdAsync(Guid id) { var r=await Full().AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id); return r is null?null:ToDto(r); }
    public Task<ServiceRequestDto?> UpdateStatusAsync(Guid id,string status)=>UpdateAsync(id,r=>r.Status=status);
    public Task<ServiceRequestDto?> UpdateNotesAsync(Guid id,string? internalNotes)=>UpdateAsync(id,r=>r.InternalNotes=TrimOrNull(internalNotes));
    public Task<ServiceRequestDto?> UpdateQuoteAsync(Guid id, ServiceRequestQuoteUpdateModel q)=>UpdateAsync(id,r=>{ r.Quote ??= new Quote{Id=Guid.NewGuid(),ServiceRequestId=r.Id,CreatedUtc=DateTime.UtcNow}; r.Quote.EstimateLow=q.EstimateLow; r.Quote.EstimateHigh=q.EstimateHigh; r.Quote.PartsNeeded=TrimOrNull(q.PartsNeeded); r.Quote.InternalQuoteNotes=TrimOrNull(q.InternalQuoteNotes); r.Quote.LaborAmount=q.LaborAmount; r.Quote.PartsAmount=q.PartsAmount; r.Quote.ShopSuppliesAmount=q.ShopSuppliesAmount; r.Quote.TotalEstimate=q.TotalEstimate; r.Quote.QuoteTemplate=TrimOrNull(q.QuoteTemplate); r.Quote.AssumptionDisclaimerText=TrimOrNull(q.AssumptionDisclaimerText); r.Quote.GoodOption=TrimOrNull(q.GoodOption); r.Quote.BetterOption=TrimOrNull(q.BetterOption); r.Quote.BestOption=TrimOrNull(q.BestOption); r.Quote.QuoteExpirationDate=q.QuoteExpirationDate; r.Quote.CustomerApprovalStatus=q.CustomerApprovalStatus; r.Quote.UpdatedUtc=DateTime.UtcNow; if(string.IsNullOrWhiteSpace(r.QuoteApprovalToken)) r.QuoteApprovalToken=NewToken(); });
    public Task<ServiceRequestDto?> UpdateScheduleAsync(Guid id, ServiceRequestScheduleUpdateModel m)=>UpdateAsync(id,r=>{ r.ScheduledStartUtc=m.ScheduledStartUtc; r.ScheduledEndUtc=m.ScheduledEndUtc; r.EstimatedDurationMinutes=m.EstimatedDurationMinutes; r.ServiceLocationType=TrimOrNull(m.ServiceLocationType); r.ScheduleNotes=TrimOrNull(m.ScheduleNotes); });

    public async Task<List<ServiceIntakeQuestionDto>> GetQuestionsAsync(string serviceType) { await SeedOperationalDataAsync(); var st=Uri.UnescapeDataString(serviceType); return await dbContext.ServiceIntakeQuestions.AsNoTracking().Where(x=>x.IsActive && x.ServiceType==st).OrderBy(x=>x.SortOrder).Select(x=>new ServiceIntakeQuestionDto{Id=x.Id,ServiceType=x.ServiceType,QuestionText=x.QuestionText,HelpText=x.HelpText,AnswerType=x.AnswerType,OptionsJson=x.OptionsJson,IsRequired=x.IsRequired,SortOrder=x.SortOrder}).ToListAsync(); }
    public async Task<List<JobChecklistItemDto>?> GetChecklistAsync(Guid id){ var r=await dbContext.ServiceRequests.Include(x=>x.ChecklistItems).SingleOrDefaultAsync(x=>x.Id==id); if(r is null)return null; if(!r.ChecklistItems.Any()){ await AddChecklistFromTemplateAsync(r,DateTime.UtcNow); await dbContext.SaveChangesAsync(); } return r.ChecklistItems.OrderBy(x=>x.SortOrder).Select(ToDto).ToList(); }
    public async Task<JobChecklistItemDto?> AddChecklistItemAsync(Guid id,string text){ var exists=await dbContext.ServiceRequests.AnyAsync(x=>x.Id==id); if(!exists)return null; var sort=(await dbContext.JobChecklistItems.Where(x=>x.ServiceRequestId==id).MaxAsync(x=>(int?)x.SortOrder)??0)+10; var item=new JobChecklistItem{Id=Guid.NewGuid(),ServiceRequestId=id,Text=text.Trim(),IsCustom=true,SortOrder=sort,CreatedUtc=DateTime.UtcNow,UpdatedUtc=DateTime.UtcNow}; dbContext.JobChecklistItems.Add(item); await dbContext.SaveChangesAsync(); return ToDto(item); }
    public async Task<JobChecklistItemDto?> UpdateChecklistItemAsync(Guid id,Guid itemId,bool completed){ var item=await dbContext.JobChecklistItems.SingleOrDefaultAsync(x=>x.ServiceRequestId==id&&x.Id==itemId); if(item is null)return null; item.IsCompleted=completed; item.CompletedUtc=completed?DateTime.UtcNow:null; item.UpdatedUtc=DateTime.UtcNow; await dbContext.SaveChangesAsync(); return ToDto(item); }
    public async Task<bool> DeleteChecklistItemAsync(Guid id,Guid itemId){ var item=await dbContext.JobChecklistItems.SingleOrDefaultAsync(x=>x.ServiceRequestId==id&&x.Id==itemId&&x.IsCustom); if(item is null)return false; dbContext.Remove(item); await dbContext.SaveChangesAsync(); return true; }
    public async Task<PaymentDto?> GetPaymentAsync(Guid id){ var exists=await dbContext.ServiceRequests.AnyAsync(x=>x.Id==id); if(!exists)return null; var p=await dbContext.Payments.AsNoTracking().SingleOrDefaultAsync(x=>x.ServiceRequestId==id); if(p is null){ var total=await dbContext.Quotes.Where(x=>x.ServiceRequestId==id).Select(x=>x.TotalEstimate).SingleOrDefaultAsync(); return new PaymentDto{AmountDue=total}; } return ToDto(p); }
    public async Task<PaymentDto?> UpdatePaymentAsync(Guid id,PaymentDto m){ var r=await dbContext.ServiceRequests.Include(x=>x.Payment).SingleOrDefaultAsync(x=>x.Id==id); if(r is null)return null; r.Payment ??= new Payment{Id=Guid.NewGuid(),ServiceRequestId=id,CreatedUtc=DateTime.UtcNow}; r.Payment.PaymentStatus=m.PaymentStatus; r.Payment.PaymentMethod=TrimOrNull(m.PaymentMethod); r.Payment.AmountDue=m.AmountDue; r.Payment.AmountPaid=m.AmountPaid; r.Payment.PaidUtc=m.PaidUtc; r.Payment.Notes=TrimOrNull(m.Notes); r.Payment.UpdatedUtc=DateTime.UtcNow; await dbContext.SaveChangesAsync(); return ToDto(r.Payment); }
    public async Task<JobRiskAssessmentDto?> GetRiskAsync(Guid id){ var exists=await dbContext.ServiceRequests.AnyAsync(x=>x.Id==id); if(!exists)return null; var r=await dbContext.JobRiskAssessments.AsNoTracking().SingleOrDefaultAsync(x=>x.ServiceRequestId==id); return r is null?new JobRiskAssessmentDto():ToDto(r); }
    public async Task<JobRiskAssessmentDto?> UpdateRiskAsync(Guid id,JobRiskAssessmentDto m){ var req=await dbContext.ServiceRequests.Include(x=>x.RiskAssessment).SingleOrDefaultAsync(x=>x.Id==id); if(req is null)return null; req.RiskAssessment ??= new JobRiskAssessment{Id=Guid.NewGuid(),ServiceRequestId=id,CreatedUtc=DateTime.UtcNow}; var r=req.RiskAssessment; r.RustConcern=m.RustConcern; r.RequiresLift=m.RequiresLift; r.CustomerSuppliedParts=m.CustomerSuppliedParts; r.KnownDifficultVehicle=m.KnownDifficultVehicle; r.EstimatedHours=m.EstimatedHours; r.SafetyCritical=m.SafetyCritical; r.NeedsAlignment=m.NeedsAlignment; r.NeedsTow=m.NeedsTow; r.MobileWorkConcern=m.MobileWorkConcern; r.Notes=TrimOrNull(m.Notes); r.RiskScore=CalculateRisk(m); r.Recommendation=Recommendation(r.RiskScore); r.UpdatedUtc=DateTime.UtcNow; await dbContext.SaveChangesAsync(); return ToDto(r); }
    public async Task<PublicRequestStatusDto?> GetPublicStatusAsync(string token){ var r=await Full().AsNoTracking().SingleOrDefaultAsync(x=>x.PublicStatusToken==token); return r is null?null:new PublicRequestStatusDto{Status=r.Status,Vehicle=$"{r.Vehicle.Year} {r.Vehicle.Make} {r.Vehicle.Model}",ServiceType=r.ServiceType,SubmittedUtc=r.CreatedUtc,ScheduledStartUtc=r.ScheduledStartUtc,ScheduledEndUtc=r.ScheduledEndUtc,EstimateLow=r.Quote?.EstimateLow,EstimateHigh=r.Quote?.EstimateHigh,TotalEstimate=r.Quote?.TotalEstimate,CustomerApprovalStatus=r.Quote?.CustomerApprovalStatus??ServiceRequestApprovalStatuses.Pending,NextStepMessage=NextStep(r)}; }
    public async Task<PublicQuoteDto?> GetPublicQuoteAsync(string token){ var r=await Full().AsNoTracking().SingleOrDefaultAsync(x=>x.QuoteApprovalToken==token); return r?.Quote is null?null:new PublicQuoteDto{Vehicle=$"{r.Vehicle.Year} {r.Vehicle.Make} {r.Vehicle.Model}",ServiceType=r.ServiceType,EstimateLow=r.Quote.EstimateLow,EstimateHigh=r.Quote.EstimateHigh,TotalEstimate=r.Quote.TotalEstimate,GoodOption=r.Quote.GoodOption,BetterOption=r.Quote.BetterOption,BestOption=r.Quote.BestOption,AssumptionDisclaimerText=r.Quote.AssumptionDisclaimerText,PartsNeeded=r.Quote.PartsNeeded,ScheduledStartUtc=r.ScheduledStartUtc,ScheduledEndUtc=r.ScheduledEndUtc,CustomerApprovalStatus=r.Quote.CustomerApprovalStatus,CustomerApprovalMessage=r.Quote.CustomerApprovalMessage}; }
    public async Task<PublicQuoteDto?> SaveQuoteDecisionAsync(string token,QuoteDecisionModel m){ var r=await Full().SingleOrDefaultAsync(x=>x.QuoteApprovalToken==token); if(r?.Quote is null)return null; r.Quote.CustomerApprovalStatus=m.Decision; r.Quote.CustomerApprovalRespondedUtc=DateTime.UtcNow; r.Quote.CustomerApprovalMessage=TrimOrNull(m.Message); if(m.Decision==ServiceRequestApprovalStatuses.Declined) r.Status=ServiceRequestStatuses.Declined; r.UpdatedUtc=DateTime.UtcNow; await dbContext.SaveChangesAsync(); return await GetPublicQuoteAsync(token); }
    public async Task<CustomerHistoryDto?> GetCustomerAsync(Guid id){ var c=await dbContext.Customers.AsNoTracking().Include(x=>x.Vehicles).Include(x=>x.ServiceRequests).ThenInclude(x=>x.Vehicle).Include(x=>x.ServiceRequests).ThenInclude(x=>x.Quote).Include(x=>x.ServiceRequests).ThenInclude(x=>x.Payment).SingleOrDefaultAsync(x=>x.Id==id); if(c is null)return null; var req=c.ServiceRequests.Select(ToDto).OrderByDescending(x=>x.CreatedAtUtc).ToList(); return new CustomerHistoryDto{Id=c.Id,Name=c.Name,Phone=c.Phone,Email=c.Email,Vehicles=c.Vehicles.Select(v=>new VehicleSummaryDto{Id=v.Id,Year=v.Year,Make=v.Make,Model=v.Model,Mileage=v.Mileage}).ToList(),Requests=req,CompletedJobs=req.Count(x=>x.Status==ServiceRequestStatuses.Completed||x.Status==ServiceRequestStatuses.Paid),OpenJobs=req.Count(x=>x.Status!=ServiceRequestStatuses.Completed&&x.Status!=ServiceRequestStatuses.Paid&&x.Status!=ServiceRequestStatuses.Canceled&&x.Status!=ServiceRequestStatuses.Declined),TotalEstimatedRevenue=req.Sum(x=>x.TotalEstimate??x.EstimateHigh??0),TotalPaidAmount=c.ServiceRequests.Sum(x=>x.Payment?.AmountPaid??0),LastServiceDate=req.Select(x=>x.ScheduledStartUtc??x.CreatedAtUtc).Max()}; }
    public async Task<VehicleHistoryDto?> GetVehicleAsync(Guid id){ var v=await dbContext.Vehicles.AsNoTracking().Include(x=>x.Customer).Include(x=>x.ServiceRequests).ThenInclude(x=>x.Customer).Include(x=>x.ServiceRequests).ThenInclude(x=>x.Vehicle).Include(x=>x.ServiceRequests).ThenInclude(x=>x.Quote).SingleOrDefaultAsync(x=>x.Id==id); if(v is null)return null; var req=v.ServiceRequests.Select(ToDto).OrderByDescending(x=>x.CreatedAtUtc).ToList(); return new VehicleHistoryDto{Id=v.Id,CustomerId=v.CustomerId,CustomerName=v.Customer?.Name??"",Year=v.Year,Make=v.Make,Model=v.Model,Mileage=v.Mileage,Requests=req,LastOilChange=req.FirstOrDefault(x=>x.ServiceType.Contains("Oil",StringComparison.OrdinalIgnoreCase) && (x.Status==ServiceRequestStatuses.Completed||x.Status==ServiceRequestStatuses.Paid))?.CreatedAtUtc,LastBrakeJob=req.FirstOrDefault(x=>x.ServiceType.Contains("Brake",StringComparison.OrdinalIgnoreCase) && (x.Status==ServiceRequestStatuses.Completed||x.Status==ServiceRequestStatuses.Paid))?.CreatedAtUtc,KnownIssues=req.Where(x=>!string.IsNullOrWhiteSpace(x.Symptoms)).Select(x=>x.Symptoms!).Take(5).ToList(),PartsHistory=req.Where(x=>!string.IsNullOrWhiteSpace(x.PartsNeeded)).Select(x=>x.PartsNeeded!).ToList()}; }

    private IQueryable<ServiceRequest> Full()=>dbContext.ServiceRequests.Include(x=>x.Customer).Include(x=>x.Vehicle).Include(x=>x.Quote).Include(x=>x.Payment).Include(x=>x.IntakeAnswers).Include(x=>x.ChecklistItems).Include(x=>x.RiskAssessment);
    private async Task<ServiceRequestDto?> UpdateAsync(Guid id,Action<ServiceRequest> apply){ var r=await Full().SingleOrDefaultAsync(x=>x.Id==id); if(r is null)return null; apply(r); r.UpdatedUtc=DateTime.UtcNow; await dbContext.SaveChangesAsync(); return ToDto(r); }
    private static string NewToken()=>Convert.ToHexString(Guid.NewGuid().ToByteArray()).ToLowerInvariant()+Convert.ToHexString(Guid.NewGuid().ToByteArray()).ToLowerInvariant();
    private async Task AddIntakeAnswersAsync(ServiceRequest sr,IEnumerable<ServiceIntakeAnswerDto>? answers,DateTime now){ if(answers is null)return; foreach(var a in answers.Where(x=>!string.IsNullOrWhiteSpace(x.QuestionText)||!string.IsNullOrWhiteSpace(x.AnswerText))) dbContext.ServiceIntakeAnswers.Add(new(){Id=Guid.NewGuid(),ServiceRequestId=sr.Id,QuestionId=a.QuestionId,QuestionText=a.QuestionText,AnswerText=TrimOrNull(a.AnswerText),CreatedUtc=now}); await Task.CompletedTask; }
    private async Task AddChecklistFromTemplateAsync(ServiceRequest sr,DateTime now){ await SeedOperationalDataAsync(); var service=sr.ServiceType.Split(',',StringSplitOptions.TrimEntries|StringSplitOptions.RemoveEmptyEntries).FirstOrDefault()??sr.ServiceType; var t=await dbContext.ChecklistTemplates.Include(x=>x.Items).Where(x=>x.IsActive&&x.ServiceType==service).OrderBy(x=>x.SortOrder).FirstOrDefaultAsync(); if(t is null)return; foreach(var i in t.Items.OrderBy(x=>x.SortOrder)) dbContext.JobChecklistItems.Add(new(){Id=Guid.NewGuid(),ServiceRequestId=sr.Id,Text=i.Text,SortOrder=i.SortOrder,CreatedUtc=now,UpdatedUtc=now}); }
    private async Task SeedOperationalDataAsync(){ if(await dbContext.ServiceIntakeQuestions.AnyAsync()) return; foreach(var (service,qs) in SeedQuestions()) { var n=0; foreach(var q in qs) dbContext.ServiceIntakeQuestions.Add(new(){Id=Guid.NewGuid(),ServiceType=service,QuestionText=q,AnswerType=IntakeAnswerTypes.Text,SortOrder=(++n)*10,IsActive=true}); } foreach(var (service,items) in SeedChecklists()){ var t=new ChecklistTemplate{Id=Guid.NewGuid(),ServiceType=service,Name=$"{service} checklist",SortOrder=10,IsActive=true}; dbContext.ChecklistTemplates.Add(t); var n=0; foreach(var item in items) dbContext.ChecklistTemplateItems.Add(new(){Id=Guid.NewGuid(),ChecklistTemplateId=t.Id,Text=item,SortOrder=(++n)*10,IsRequired=true}); } await dbContext.SaveChangesAsync(); }
    private static IEnumerable<(string,string[])> SeedQuestions()=>[("Brakes / Rotors",["Front, rear, or both?","Do you hear grinding?","Does the steering wheel shake when braking?","Does the brake pedal feel soft?","Are any brake warning lights on?"]),("Oil Change",["Synthetic, synthetic blend, conventional, or not sure?","Do you know the engine size?","Last oil change mileage?","Any leaks or burning oil smell?"]),("No-Start Diagnosis",["Does the engine crank?","Do you hear clicking?","How old is the battery?","Do lights/radio work?","Any warning lights?"]),("Starter Replacement",["Does it click once when turning the key?","Does the engine crank at all?","Has the battery been tested?","Is the issue intermittent?"]),("Suspension Diagnosis",["What noise do you hear?","Which side does it come from?","Does it happen over bumps, turning, braking, or all the time?","Any steering wheel vibration?"]),("Wheel Bearing Replacement",["Which side sounds noisy?","Does the noise change when turning?","Is there wheel play?","Does the noise increase with speed?"]),("CV Axle Replacement",["Do you hear clicking while turning?","Which side?","Is the boot torn or leaking grease?","Any vibration while accelerating?"]),("General Diagnosis",["What is the main concern?","When did it start?","Is the vehicle safe to drive?","Any recent repairs?"])];
    private static IEnumerable<(string,string[])> SeedChecklists()=>[("Oil Change",["Confirm oil type and capacity","Confirm filter","Drain oil","Replace filter","Fill oil","Check oil level","Start engine and check for leaks","Reset oil life","Record final mileage"]),("Brakes / Rotors",["Confirm front/rear/both","Inspect pads","Inspect rotors","Inspect calipers","Inspect slide pins","Clean and lube hardware","Install pads/rotors","Torque wheels","Test drive","Final brake safety check"]),("Suspension Diagnosis",["Inspect ball joints","Inspect tie rods","Inspect control arms","Inspect sway bar links","Inspect struts/shocks","Check wheel bearing play","Note alignment recommendation if needed"]),("No-Start Diagnosis",["Verify customer concern","Test battery","Check battery terminals","Check starter signal","Check fuses/relays if needed","Record diagnosis","Recommend next repair"]),("Starter Replacement",["Disconnect battery","Remove starter","Inspect connections","Install new starter","Reconnect battery","Test start","Final inspection"])];
    private static int CalculateRisk(JobRiskAssessmentDto r)=>(r.RustConcern?2:0)+(r.RequiresLift?3:0)+(r.CustomerSuppliedParts?1:0)+(r.KnownDifficultVehicle?2:0)+(r.EstimatedHours>5?3:r.EstimatedHours>3?2:0)+(r.SafetyCritical?2:0)+(r.NeedsAlignment?1:0)+(r.NeedsTow?3:0)+(r.MobileWorkConcern?2:0);
    private static string Recommendation(int score)=>score<=2?RiskRecommendations.GoodFit:score<=5?RiskRecommendations.Maybe:RiskRecommendations.DeclineOrReferOut;
    private static string NextStep(ServiceRequest r)=>r.Status switch{ var s when s==ServiceRequestStatuses.New=>"We received your request and will review it soon.", var s when s==ServiceRequestStatuses.Quoted=>"Your quote is ready for review.", var s when s==ServiceRequestStatuses.Scheduled=>"Your service is scheduled.", var s when s==ServiceRequestStatuses.Completed=>"Service is complete. Thanks for choosing 2nd Shift Auto Care.", _=>"We will follow up with the next step."};
    private static string? TrimOrNull(string? v)=>string.IsNullOrWhiteSpace(v)?null:v.Trim();
    private static JobChecklistItemDto ToDto(JobChecklistItem x)=>new(){Id=x.Id,Text=x.Text,IsCompleted=x.IsCompleted,CompletedUtc=x.CompletedUtc,SortOrder=x.SortOrder,IsCustom=x.IsCustom};
    private static PaymentDto ToDto(Payment p)=>new(){PaymentStatus=p.PaymentStatus,PaymentMethod=p.PaymentMethod,AmountDue=p.AmountDue,AmountPaid=p.AmountPaid,PaidUtc=p.PaidUtc,Notes=p.Notes};
    private static JobRiskAssessmentDto ToDto(JobRiskAssessment r)=>new(){RustConcern=r.RustConcern,RequiresLift=r.RequiresLift,CustomerSuppliedParts=r.CustomerSuppliedParts,KnownDifficultVehicle=r.KnownDifficultVehicle,EstimatedHours=r.EstimatedHours,SafetyCritical=r.SafetyCritical,NeedsAlignment=r.NeedsAlignment,NeedsTow=r.NeedsTow,MobileWorkConcern=r.MobileWorkConcern,RiskScore=r.RiskScore,Recommendation=r.Recommendation,Notes=r.Notes};
    private static ServiceRequestDto ToDto(ServiceRequest r)=>new(){Id=r.Id,CustomerId=r.CustomerId,VehicleId=r.VehicleId,CustomerName=r.Customer.Name,Phone=r.Customer.Phone,Email=r.Customer.Email,VehicleYear=r.Vehicle.Year,VehicleMake=r.Vehicle.Make,VehicleModel=r.Vehicle.Model,Mileage=r.Vehicle.Mileage,ServiceType=r.ServiceType,Symptoms=r.Symptoms,PreferredAvailability=r.PreferredAvailability,ServiceSpecificAnswers=r.ServiceSpecificAnswers,UrgencyLevel=r.UrgencyLevel,IsVehicleDrivable=r.IsVehicleDrivable,VehicleLocation=r.VehicleLocation,ConsentAccepted=r.ConsentAccepted,WantsPhotoUploadLater=r.WantsPhotoUploadLater,Status=r.Status,IsArchived=r.IsArchived,PublicStatusToken=r.PublicStatusToken,QuoteApprovalToken=r.QuoteApprovalToken,ScheduledStartUtc=r.ScheduledStartUtc,ScheduledEndUtc=r.ScheduledEndUtc,EstimatedDurationMinutes=r.EstimatedDurationMinutes,ServiceLocationType=r.ServiceLocationType,ScheduleNotes=r.ScheduleNotes,EstimateLow=r.Quote?.EstimateLow,EstimateHigh=r.Quote?.EstimateHigh,PartsNeeded=r.Quote?.PartsNeeded,InternalQuoteNotes=r.Quote?.InternalQuoteNotes,LaborAmount=r.Quote?.LaborAmount,PartsAmount=r.Quote?.PartsAmount,ShopSuppliesAmount=r.Quote?.ShopSuppliesAmount,TotalEstimate=r.Quote?.TotalEstimate,QuoteTemplate=r.Quote?.QuoteTemplate,AssumptionDisclaimerText=r.Quote?.AssumptionDisclaimerText,GoodOption=r.Quote?.GoodOption,BetterOption=r.Quote?.BetterOption,BestOption=r.Quote?.BestOption,QuoteExpirationDate=r.Quote?.QuoteExpirationDate,CustomerApprovalStatus=r.Quote?.CustomerApprovalStatus??ServiceRequestApprovalStatuses.Pending,CustomerApprovalRespondedUtc=r.Quote?.CustomerApprovalRespondedUtc,CustomerApprovalMessage=r.Quote?.CustomerApprovalMessage,PaymentStatus=r.Payment?.PaymentStatus,InternalNotes=r.InternalNotes,CreatedAtUtc=r.CreatedUtc,UpdatedAtUtc=r.UpdatedUtc,IntakeAnswers=r.IntakeAnswers.OrderBy(x=>x.CreatedUtc).Select(x=>new ServiceIntakeAnswerDto{QuestionId=x.QuestionId,QuestionText=x.QuestionText,AnswerText=x.AnswerText}).ToList()};
}

public sealed class ServiceRequestQuery { public string? Search { get; set; } public string? Status { get; set; } public string? ServiceType { get; set; } public string? PaymentStatus { get; set; } public string? ScheduledFilter { get; set; } public DateTime? FromDate { get; set; } public DateTime? ToDate { get; set; } public bool IncludeArchived { get; set; } public string? Sort { get; set; } }
