// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SecondShiftAutoCare.Api.Data;

#nullable disable

namespace SecondShiftAutoCare.Api.Migrations
{
    [DbContext(typeof(ServiceRequestDbContext))]
    [Migration("20260629120000_AddAdminNewRequestNotifications")]
    partial class AddAdminNewRequestNotifications
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");
#pragma warning restore 612, 618
        }
    }
}
