using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SecondShiftAutoCare.Api.Migrations;

public partial class RefactorServiceRequestDomain : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(name: "Customers", schema: "dbo", columns: table => new
        {
            Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
            Name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
            Phone = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: false),
            Email = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: true),
            CreatedUtc = table.Column<DateTime>(type: "datetime2", nullable: false, defaultValueSql: "SYSUTCDATETIME()"),
            UpdatedUtc = table.Column<DateTime>(type: "datetime2", nullable: false, defaultValueSql: "SYSUTCDATETIME()")
        }, constraints: table => table.PrimaryKey("PK_Customers", x => x.Id));

        migrationBuilder.CreateTable(name: "Vehicles", schema: "dbo", columns: table => new
        {
            Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
            CustomerId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
            Year = table.Column<int>(type: "int", nullable: false),
            Make = table.Column<string>(type: "nvarchar(75)", maxLength: 75, nullable: false),
            Model = table.Column<string>(type: "nvarchar(75)", maxLength: 75, nullable: false),
            Mileage = table.Column<int>(type: "int", nullable: true),
            CreatedUtc = table.Column<DateTime>(type: "datetime2", nullable: false, defaultValueSql: "SYSUTCDATETIME()"),
            UpdatedUtc = table.Column<DateTime>(type: "datetime2", nullable: false, defaultValueSql: "SYSUTCDATETIME()")
        }, constraints: table => { table.PrimaryKey("PK_Vehicles", x => x.Id); table.ForeignKey(name: "FK_Vehicles_Customers_CustomerId", column: x => x.CustomerId, principalSchema: "dbo", principalTable: "Customers", principalColumn: "Id", onDelete: ReferentialAction.Restrict); });

        migrationBuilder.CreateTable(name: "Quotes", schema: "dbo", columns: table => new
        {
            Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), ServiceRequestId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
            EstimateLow = table.Column<decimal>(type: "decimal(8,2)", precision: 8, scale: 2, nullable: true), EstimateHigh = table.Column<decimal>(type: "decimal(8,2)", precision: 8, scale: 2, nullable: true), LaborAmount = table.Column<decimal>(type: "decimal(8,2)", precision: 8, scale: 2, nullable: true), PartsAmount = table.Column<decimal>(type: "decimal(8,2)", precision: 8, scale: 2, nullable: true), ShopSuppliesAmount = table.Column<decimal>(type: "decimal(8,2)", precision: 8, scale: 2, nullable: true), TotalEstimate = table.Column<decimal>(type: "decimal(8,2)", precision: 8, scale: 2, nullable: true),
            PartsNeeded = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true), InternalQuoteNotes = table.Column<string>(type: "nvarchar(4000)", maxLength: 4000, nullable: true), QuoteTemplate = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true), AssumptionDisclaimerText = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true), GoodOption = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true), BetterOption = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true), BestOption = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true), CustomerApprovalStatus = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false, defaultValue: "Pending"), QuoteExpirationDate = table.Column<DateTime>(type: "datetime2", nullable: true), CreatedUtc = table.Column<DateTime>(type: "datetime2", nullable: false, defaultValueSql: "SYSUTCDATETIME()"), UpdatedUtc = table.Column<DateTime>(type: "datetime2", nullable: false, defaultValueSql: "SYSUTCDATETIME()")
        }, constraints: table => { table.PrimaryKey("PK_Quotes", x => x.Id); });

        migrationBuilder.AddColumn<Guid>(name: "CustomerId", schema: "dbo", table: "ServiceRequests", type: "uniqueidentifier", nullable: true);
        migrationBuilder.AddColumn<Guid>(name: "VehicleId", schema: "dbo", table: "ServiceRequests", type: "uniqueidentifier", nullable: true);
        migrationBuilder.AddColumn<string>(name: "Notes", schema: "dbo", table: "ServiceRequests", type: "nvarchar(2000)", maxLength: 2000, nullable: true);

        migrationBuilder.Sql(@"
DECLARE @map TABLE (ServiceRequestId uniqueidentifier, CustomerId uniqueidentifier, VehicleId uniqueidentifier);
INSERT INTO @map SELECT Id, NEWID(), NEWID() FROM dbo.ServiceRequests WHERE CustomerId IS NULL OR VehicleId IS NULL;
INSERT INTO dbo.Customers (Id, Name, Phone, Email, CreatedUtc, UpdatedUtc)
SELECT m.CustomerId, sr.CustomerName, sr.Phone, sr.Email, sr.CreatedUtc, sr.UpdatedUtc FROM dbo.ServiceRequests sr JOIN @map m ON sr.Id = m.ServiceRequestId;
INSERT INTO dbo.Vehicles (Id, CustomerId, [Year], Make, Model, Mileage, CreatedUtc, UpdatedUtc)
SELECT m.VehicleId, m.CustomerId, sr.VehicleYear, sr.VehicleMake, sr.VehicleModel, sr.Mileage, sr.CreatedUtc, sr.UpdatedUtc FROM dbo.ServiceRequests sr JOIN @map m ON sr.Id = m.ServiceRequestId;
UPDATE sr SET CustomerId = m.CustomerId, VehicleId = m.VehicleId FROM dbo.ServiceRequests sr JOIN @map m ON sr.Id = m.ServiceRequestId;
INSERT INTO dbo.Quotes (Id, ServiceRequestId, EstimateLow, EstimateHigh, LaborAmount, PartsAmount, ShopSuppliesAmount, TotalEstimate, PartsNeeded, InternalQuoteNotes, QuoteTemplate, AssumptionDisclaimerText, GoodOption, BetterOption, BestOption, CustomerApprovalStatus, QuoteExpirationDate, CreatedUtc, UpdatedUtc)
SELECT NEWID(), sr.Id, sr.EstimateLow, sr.EstimateHigh, sr.LaborAmount, sr.PartsAmount, sr.ShopSuppliesAmount, sr.TotalEstimate, sr.PartsNeeded, sr.InternalQuoteNotes, sr.QuoteTemplate, sr.AssumptionDisclaimerText, sr.GoodOption, sr.BetterOption, sr.BestOption, sr.CustomerApprovalStatus, sr.QuoteExpirationDate, sr.CreatedUtc, sr.UpdatedUtc FROM dbo.ServiceRequests sr WHERE NOT EXISTS (SELECT 1 FROM dbo.Quotes q WHERE q.ServiceRequestId = sr.Id);
");
        migrationBuilder.AlterColumn<Guid>(name: "CustomerId", schema: "dbo", table: "ServiceRequests", type: "uniqueidentifier", nullable: false, oldClrType: typeof(Guid), oldType: "uniqueidentifier", oldNullable: true);
        migrationBuilder.AlterColumn<Guid>(name: "VehicleId", schema: "dbo", table: "ServiceRequests", type: "uniqueidentifier", nullable: false, oldClrType: typeof(Guid), oldType: "uniqueidentifier", oldNullable: true);
        migrationBuilder.AlterColumn<string>(name: "Symptoms", schema: "dbo", table: "ServiceRequests", type: "nvarchar(2000)", maxLength: 2000, nullable: true, oldClrType: typeof(string), oldType: "nvarchar(2000)", oldMaxLength: 2000);

        foreach (var c in new[] { "CustomerName", "Phone", "Email", "VehicleYear", "VehicleMake", "VehicleModel", "Mileage", "AlternateContactName", "AlternateContactPhone", "EstimateLow", "EstimateHigh", "PartsNeeded", "InternalQuoteNotes", "LaborAmount", "PartsAmount", "ShopSuppliesAmount", "TotalEstimate", "QuoteTemplate", "AssumptionDisclaimerText", "GoodOption", "BetterOption", "BestOption", "QuoteExpirationDate", "CustomerApprovalStatus" })
            migrationBuilder.DropColumn(name: c, schema: "dbo", table: "ServiceRequests");

        migrationBuilder.CreateIndex(name: "IX_ServiceRequests_CustomerId", schema: "dbo", table: "ServiceRequests", column: "CustomerId"); migrationBuilder.CreateIndex(name: "IX_ServiceRequests_VehicleId", schema: "dbo", table: "ServiceRequests", column: "VehicleId"); migrationBuilder.CreateIndex(name: "IX_Vehicles_CustomerId", schema: "dbo", table: "Vehicles", column: "CustomerId"); migrationBuilder.CreateIndex(name: "IX_Vehicles_Year", schema: "dbo", table: "Vehicles", column: "Year"); migrationBuilder.CreateIndex(name: "IX_Vehicles_Make_Model", schema: "dbo", table: "Vehicles", columns: new[] { "Make", "Model" }); migrationBuilder.CreateIndex(name: "IX_Customers_Phone", schema: "dbo", table: "Customers", column: "Phone"); migrationBuilder.CreateIndex(name: "IX_Customers_Email", schema: "dbo", table: "Customers", column: "Email"); migrationBuilder.CreateIndex(name: "IX_Quotes_ServiceRequestId", schema: "dbo", table: "Quotes", column: "ServiceRequestId", unique: true);
        migrationBuilder.AddForeignKey(name: "FK_ServiceRequests_Customers_CustomerId", schema: "dbo", table: "ServiceRequests", column: "CustomerId", principalSchema: "dbo", principalTable: "Customers", principalColumn: "Id", onDelete: ReferentialAction.Restrict); migrationBuilder.AddForeignKey(name: "FK_ServiceRequests_Vehicles_VehicleId", schema: "dbo", table: "ServiceRequests", column: "VehicleId", principalSchema: "dbo", principalTable: "Vehicles", principalColumn: "Id", onDelete: ReferentialAction.Restrict); migrationBuilder.AddForeignKey(name: "FK_Quotes_ServiceRequests_ServiceRequestId", schema: "dbo", table: "Quotes", column: "ServiceRequestId", principalSchema: "dbo", principalTable: "ServiceRequests", principalColumn: "Id", onDelete: ReferentialAction.Cascade);
        migrationBuilder.CreateTable(name: "ServiceCatalogItems", schema: "dbo", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), Name = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: false), Description = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true), IsActive = table.Column<bool>(type: "bit", nullable: false), SortOrder = table.Column<int>(type: "int", nullable: false), CreatedUtc = table.Column<DateTime>(type: "datetime2", nullable: false), UpdatedUtc = table.Column<DateTime>(type: "datetime2", nullable: false) }, constraints: table => table.PrimaryKey("PK_ServiceCatalogItems", x => x.Id));
        migrationBuilder.CreateIndex(name: "IX_ServiceCatalogItems_Name", schema: "dbo", table: "ServiceCatalogItems", column: "Name", unique: true);
        migrationBuilder.CreateTable(name: "VehicleMakes", schema: "dbo", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), Name = table.Column<string>(type: "nvarchar(75)", maxLength: 75, nullable: false), IsActive = table.Column<bool>(type: "bit", nullable: false) }, constraints: table => table.PrimaryKey("PK_VehicleMakes", x => x.Id));
        migrationBuilder.CreateTable(name: "VehicleModels", schema: "dbo", columns: table => new { Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false), VehicleMakeId = table.Column<Guid>(type: "uniqueidentifier", nullable: false), Name = table.Column<string>(type: "nvarchar(75)", maxLength: 75, nullable: false), StartYear = table.Column<int>(type: "int", nullable: false), EndYear = table.Column<int>(type: "int", nullable: true), IsActive = table.Column<bool>(type: "bit", nullable: false) }, constraints: table => { table.PrimaryKey("PK_VehicleModels", x => x.Id); table.ForeignKey(name: "FK_VehicleModels_VehicleMakes_VehicleMakeId", column: x => x.VehicleMakeId, principalSchema: "dbo", principalTable: "VehicleMakes", principalColumn: "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateIndex(name: "IX_VehicleMakes_Name", schema: "dbo", table: "VehicleMakes", column: "Name", unique: true); migrationBuilder.CreateIndex(name: "IX_VehicleModels_VehicleMakeId", schema: "dbo", table: "VehicleModels", column: "VehicleMakeId"); migrationBuilder.CreateIndex(name: "IX_VehicleModels_Name", schema: "dbo", table: "VehicleModels", column: "Name");

        migrationBuilder.Sql(@"
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'AC Basic Diagnosis') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'AC Basic Diagnosis', 1, 1, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Alternator Replacement') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Alternator Replacement', 1, 2, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Ball Joint Replacement') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Ball Joint Replacement', 1, 3, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Battery / Charging System Test') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Battery / Charging System Test', 1, 4, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Battery Replacement') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Battery Replacement', 1, 5, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Brake Caliper Replacement') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Brake Caliper Replacement', 1, 6, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Brake Inspection') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Brake Inspection', 1, 7, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Brakes / Rotors') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Brakes / Rotors', 1, 8, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Cabin Air Filter') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Cabin Air Filter', 1, 9, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Check Engine Light Basic Diagnosis') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Check Engine Light Basic Diagnosis', 1, 10, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Coolant Hose Replacement') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Coolant Hose Replacement', 1, 11, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'CV Axle Replacement') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'CV Axle Replacement', 1, 12, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Engine Air Filter') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Engine Air Filter', 1, 13, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'General Diagnosis') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'General Diagnosis', 1, 14, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Headlight / Taillight Bulb Replacement') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Headlight / Taillight Bulb Replacement', 1, 15, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'No-Start Diagnosis') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'No-Start Diagnosis', 1, 16, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Oil Change') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Oil Change', 1, 17, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Pre-Trip Inspection') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Pre-Trip Inspection', 1, 18, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Serpentine Belt') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Serpentine Belt', 1, 19, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Spark Plugs') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Spark Plugs', 1, 20, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Starter Replacement') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Starter Replacement', 1, 21, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Suspension Diagnosis') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Suspension Diagnosis', 1, 22, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Sway Bar Link Replacement') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Sway Bar Link Replacement', 1, 23, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Thermostat Replacement') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Thermostat Replacement', 1, 24, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Tie Rod End Replacement') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Tie Rod End Replacement', 1, 25, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Tire Rotation') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Tire Rotation', 1, 26, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Used Vehicle Inspection') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Used Vehicle Inspection', 1, 27, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Water Pump Replacement') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Water Pump Replacement', 1, 28, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Wheel Bearing Replacement') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Wheel Bearing Replacement', 1, 29, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.ServiceCatalogItems WHERE Name = 'Wiper Blades') INSERT INTO dbo.ServiceCatalogItems (Id, Name, IsActive, SortOrder, CreatedUtc, UpdatedUtc) VALUES (NEWID(), 'Wiper Blades', 1, 30, SYSUTCDATETIME(), SYSUTCDATETIME());
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Acura') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Acura', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Audi') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Audi', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'BMW') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'BMW', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Buick') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Buick', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Cadillac') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Cadillac', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Chevrolet') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Chevrolet', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Chrysler') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Chrysler', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Dodge') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Dodge', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Ford') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Ford', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'GMC') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'GMC', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Honda') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Honda', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Hyundai') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Hyundai', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Jeep') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Jeep', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Kia') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Kia', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Lexus') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Lexus', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Lincoln') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Lincoln', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Mazda') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Mazda', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Mercedes-Benz') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Mercedes-Benz', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Nissan') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Nissan', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Ram') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Ram', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Subaru') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Subaru', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Toyota') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Toyota', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Volkswagen') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Volkswagen', 1);
IF NOT EXISTS (SELECT 1 FROM dbo.VehicleMakes WHERE Name = 'Volvo') INSERT INTO dbo.VehicleMakes (Id, Name, IsActive) VALUES (NEWID(), 'Volvo', 1);
DECLARE @makeId0 uniqueidentifier; SELECT @makeId0 = Id FROM dbo.VehicleMakes WHERE Name = 'Acura'; IF @makeId0 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId0 AND Name = 'ILX') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId0, 'ILX', 2013, 2022, 1);
DECLARE @makeId1 uniqueidentifier; SELECT @makeId1 = Id FROM dbo.VehicleMakes WHERE Name = 'Acura'; IF @makeId1 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId1 AND Name = 'MDX') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId1, 'MDX', 2001, NULL, 1);
DECLARE @makeId2 uniqueidentifier; SELECT @makeId2 = Id FROM dbo.VehicleMakes WHERE Name = 'Acura'; IF @makeId2 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId2 AND Name = 'RDX') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId2, 'RDX', 2007, NULL, 1);
DECLARE @makeId3 uniqueidentifier; SELECT @makeId3 = Id FROM dbo.VehicleMakes WHERE Name = 'Acura'; IF @makeId3 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId3 AND Name = 'TLX') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId3, 'TLX', 2015, NULL, 1);
DECLARE @makeId4 uniqueidentifier; SELECT @makeId4 = Id FROM dbo.VehicleMakes WHERE Name = 'Audi'; IF @makeId4 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId4 AND Name = 'A3') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId4, 'A3', 2006, NULL, 1);
DECLARE @makeId5 uniqueidentifier; SELECT @makeId5 = Id FROM dbo.VehicleMakes WHERE Name = 'Audi'; IF @makeId5 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId5 AND Name = 'A4') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId5, 'A4', 1996, NULL, 1);
DECLARE @makeId6 uniqueidentifier; SELECT @makeId6 = Id FROM dbo.VehicleMakes WHERE Name = 'Audi'; IF @makeId6 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId6 AND Name = 'Q5') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId6, 'Q5', 2009, NULL, 1);
DECLARE @makeId7 uniqueidentifier; SELECT @makeId7 = Id FROM dbo.VehicleMakes WHERE Name = 'Audi'; IF @makeId7 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId7 AND Name = 'Q7') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId7, 'Q7', 2007, NULL, 1);
DECLARE @makeId8 uniqueidentifier; SELECT @makeId8 = Id FROM dbo.VehicleMakes WHERE Name = 'BMW'; IF @makeId8 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId8 AND Name = '3 Series') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId8, '3 Series', 1975, NULL, 1);
DECLARE @makeId9 uniqueidentifier; SELECT @makeId9 = Id FROM dbo.VehicleMakes WHERE Name = 'BMW'; IF @makeId9 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId9 AND Name = '5 Series') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId9, '5 Series', 1972, NULL, 1);
DECLARE @makeId10 uniqueidentifier; SELECT @makeId10 = Id FROM dbo.VehicleMakes WHERE Name = 'BMW'; IF @makeId10 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId10 AND Name = 'X3') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId10, 'X3', 2004, NULL, 1);
DECLARE @makeId11 uniqueidentifier; SELECT @makeId11 = Id FROM dbo.VehicleMakes WHERE Name = 'BMW'; IF @makeId11 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId11 AND Name = 'X5') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId11, 'X5', 2000, NULL, 1);
DECLARE @makeId12 uniqueidentifier; SELECT @makeId12 = Id FROM dbo.VehicleMakes WHERE Name = 'Buick'; IF @makeId12 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId12 AND Name = 'Enclave') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId12, 'Enclave', 2008, NULL, 1);
DECLARE @makeId13 uniqueidentifier; SELECT @makeId13 = Id FROM dbo.VehicleMakes WHERE Name = 'Buick'; IF @makeId13 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId13 AND Name = 'Encore') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId13, 'Encore', 2013, NULL, 1);
DECLARE @makeId14 uniqueidentifier; SELECT @makeId14 = Id FROM dbo.VehicleMakes WHERE Name = 'Buick'; IF @makeId14 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId14 AND Name = 'Envision') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId14, 'Envision', 2016, NULL, 1);
DECLARE @makeId15 uniqueidentifier; SELECT @makeId15 = Id FROM dbo.VehicleMakes WHERE Name = 'Buick'; IF @makeId15 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId15 AND Name = 'LaCrosse') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId15, 'LaCrosse', 2005, 2019, 1);
DECLARE @makeId16 uniqueidentifier; SELECT @makeId16 = Id FROM dbo.VehicleMakes WHERE Name = 'Cadillac'; IF @makeId16 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId16 AND Name = 'Escalade') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId16, 'Escalade', 1999, NULL, 1);
DECLARE @makeId17 uniqueidentifier; SELECT @makeId17 = Id FROM dbo.VehicleMakes WHERE Name = 'Cadillac'; IF @makeId17 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId17 AND Name = 'CTS') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId17, 'CTS', 2003, 2019, 1);
DECLARE @makeId18 uniqueidentifier; SELECT @makeId18 = Id FROM dbo.VehicleMakes WHERE Name = 'Cadillac'; IF @makeId18 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId18 AND Name = 'XT4') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId18, 'XT4', 2019, NULL, 1);
DECLARE @makeId19 uniqueidentifier; SELECT @makeId19 = Id FROM dbo.VehicleMakes WHERE Name = 'Cadillac'; IF @makeId19 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId19 AND Name = 'XT5') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId19, 'XT5', 2017, NULL, 1);
DECLARE @makeId20 uniqueidentifier; SELECT @makeId20 = Id FROM dbo.VehicleMakes WHERE Name = 'Chevrolet'; IF @makeId20 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId20 AND Name = 'Colorado') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId20, 'Colorado', 2004, NULL, 1);
DECLARE @makeId21 uniqueidentifier; SELECT @makeId21 = Id FROM dbo.VehicleMakes WHERE Name = 'Chevrolet'; IF @makeId21 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId21 AND Name = 'Equinox') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId21, 'Equinox', 2005, NULL, 1);
DECLARE @makeId22 uniqueidentifier; SELECT @makeId22 = Id FROM dbo.VehicleMakes WHERE Name = 'Chevrolet'; IF @makeId22 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId22 AND Name = 'Malibu') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId22, 'Malibu', 1997, NULL, 1);
DECLARE @makeId23 uniqueidentifier; SELECT @makeId23 = Id FROM dbo.VehicleMakes WHERE Name = 'Chevrolet'; IF @makeId23 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId23 AND Name = 'Silverado') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId23, 'Silverado', 1999, NULL, 1);
DECLARE @makeId24 uniqueidentifier; SELECT @makeId24 = Id FROM dbo.VehicleMakes WHERE Name = 'Chevrolet'; IF @makeId24 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId24 AND Name = 'Suburban') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId24, 'Suburban', 1970, NULL, 1);
DECLARE @makeId25 uniqueidentifier; SELECT @makeId25 = Id FROM dbo.VehicleMakes WHERE Name = 'Chevrolet'; IF @makeId25 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId25 AND Name = 'Tahoe') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId25, 'Tahoe', 1995, NULL, 1);
DECLARE @makeId26 uniqueidentifier; SELECT @makeId26 = Id FROM dbo.VehicleMakes WHERE Name = 'Chevrolet'; IF @makeId26 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId26 AND Name = 'Traverse') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId26, 'Traverse', 2009, NULL, 1);
DECLARE @makeId27 uniqueidentifier; SELECT @makeId27 = Id FROM dbo.VehicleMakes WHERE Name = 'Chrysler'; IF @makeId27 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId27 AND Name = '200') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId27, '200', 2011, 2017, 1);
DECLARE @makeId28 uniqueidentifier; SELECT @makeId28 = Id FROM dbo.VehicleMakes WHERE Name = 'Chrysler'; IF @makeId28 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId28 AND Name = '300') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId28, '300', 2005, 2023, 1);
DECLARE @makeId29 uniqueidentifier; SELECT @makeId29 = Id FROM dbo.VehicleMakes WHERE Name = 'Chrysler'; IF @makeId29 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId29 AND Name = 'Pacifica') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId29, 'Pacifica', 2017, NULL, 1);
DECLARE @makeId30 uniqueidentifier; SELECT @makeId30 = Id FROM dbo.VehicleMakes WHERE Name = 'Chrysler'; IF @makeId30 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId30 AND Name = 'Town & Country') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId30, 'Town & Country', 1990, 2016, 1);
DECLARE @makeId31 uniqueidentifier; SELECT @makeId31 = Id FROM dbo.VehicleMakes WHERE Name = 'Dodge'; IF @makeId31 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId31 AND Name = 'Challenger') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId31, 'Challenger', 2008, 2023, 1);
DECLARE @makeId32 uniqueidentifier; SELECT @makeId32 = Id FROM dbo.VehicleMakes WHERE Name = 'Dodge'; IF @makeId32 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId32 AND Name = 'Charger') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId32, 'Charger', 2006, 2023, 1);
DECLARE @makeId33 uniqueidentifier; SELECT @makeId33 = Id FROM dbo.VehicleMakes WHERE Name = 'Dodge'; IF @makeId33 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId33 AND Name = 'Durango') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId33, 'Durango', 1998, NULL, 1);
DECLARE @makeId34 uniqueidentifier; SELECT @makeId34 = Id FROM dbo.VehicleMakes WHERE Name = 'Dodge'; IF @makeId34 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId34 AND Name = 'Grand Caravan') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId34, 'Grand Caravan', 1987, 2020, 1);
DECLARE @makeId35 uniqueidentifier; SELECT @makeId35 = Id FROM dbo.VehicleMakes WHERE Name = 'Ford'; IF @makeId35 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId35 AND Name = 'Escape') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId35, 'Escape', 2001, NULL, 1);
DECLARE @makeId36 uniqueidentifier; SELECT @makeId36 = Id FROM dbo.VehicleMakes WHERE Name = 'Ford'; IF @makeId36 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId36 AND Name = 'Explorer') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId36, 'Explorer', 1991, NULL, 1);
DECLARE @makeId37 uniqueidentifier; SELECT @makeId37 = Id FROM dbo.VehicleMakes WHERE Name = 'Ford'; IF @makeId37 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId37 AND Name = 'F-150') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId37, 'F-150', 1975, NULL, 1);
DECLARE @makeId38 uniqueidentifier; SELECT @makeId38 = Id FROM dbo.VehicleMakes WHERE Name = 'Ford'; IF @makeId38 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId38 AND Name = 'Focus') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId38, 'Focus', 2000, 2018, 1);
DECLARE @makeId39 uniqueidentifier; SELECT @makeId39 = Id FROM dbo.VehicleMakes WHERE Name = 'Ford'; IF @makeId39 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId39 AND Name = 'Fusion') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId39, 'Fusion', 2006, 2020, 1);
DECLARE @makeId40 uniqueidentifier; SELECT @makeId40 = Id FROM dbo.VehicleMakes WHERE Name = 'Ford'; IF @makeId40 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId40 AND Name = 'Mustang') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId40, 'Mustang', 1970, NULL, 1);
DECLARE @makeId41 uniqueidentifier; SELECT @makeId41 = Id FROM dbo.VehicleMakes WHERE Name = 'GMC'; IF @makeId41 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId41 AND Name = 'Acadia') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId41, 'Acadia', 2007, NULL, 1);
DECLARE @makeId42 uniqueidentifier; SELECT @makeId42 = Id FROM dbo.VehicleMakes WHERE Name = 'GMC'; IF @makeId42 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId42 AND Name = 'Canyon') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId42, 'Canyon', 2004, NULL, 1);
DECLARE @makeId43 uniqueidentifier; SELECT @makeId43 = Id FROM dbo.VehicleMakes WHERE Name = 'GMC'; IF @makeId43 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId43 AND Name = 'Sierra') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId43, 'Sierra', 1999, NULL, 1);
DECLARE @makeId44 uniqueidentifier; SELECT @makeId44 = Id FROM dbo.VehicleMakes WHERE Name = 'GMC'; IF @makeId44 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId44 AND Name = 'Terrain') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId44, 'Terrain', 2010, NULL, 1);
DECLARE @makeId45 uniqueidentifier; SELECT @makeId45 = Id FROM dbo.VehicleMakes WHERE Name = 'GMC'; IF @makeId45 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId45 AND Name = 'Yukon') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId45, 'Yukon', 1992, NULL, 1);
DECLARE @makeId46 uniqueidentifier; SELECT @makeId46 = Id FROM dbo.VehicleMakes WHERE Name = 'Honda'; IF @makeId46 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId46 AND Name = 'Accord') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId46, 'Accord', 1976, NULL, 1);
DECLARE @makeId47 uniqueidentifier; SELECT @makeId47 = Id FROM dbo.VehicleMakes WHERE Name = 'Honda'; IF @makeId47 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId47 AND Name = 'Civic') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId47, 'Civic', 1973, NULL, 1);
DECLARE @makeId48 uniqueidentifier; SELECT @makeId48 = Id FROM dbo.VehicleMakes WHERE Name = 'Honda'; IF @makeId48 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId48 AND Name = 'CR-V') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId48, 'CR-V', 1997, NULL, 1);
DECLARE @makeId49 uniqueidentifier; SELECT @makeId49 = Id FROM dbo.VehicleMakes WHERE Name = 'Honda'; IF @makeId49 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId49 AND Name = 'Odyssey') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId49, 'Odyssey', 1995, NULL, 1);
DECLARE @makeId50 uniqueidentifier; SELECT @makeId50 = Id FROM dbo.VehicleMakes WHERE Name = 'Honda'; IF @makeId50 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId50 AND Name = 'Pilot') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId50, 'Pilot', 2003, NULL, 1);
DECLARE @makeId51 uniqueidentifier; SELECT @makeId51 = Id FROM dbo.VehicleMakes WHERE Name = 'Hyundai'; IF @makeId51 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId51 AND Name = 'Elantra') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId51, 'Elantra', 1992, NULL, 1);
DECLARE @makeId52 uniqueidentifier; SELECT @makeId52 = Id FROM dbo.VehicleMakes WHERE Name = 'Hyundai'; IF @makeId52 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId52 AND Name = 'Santa Fe') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId52, 'Santa Fe', 2001, NULL, 1);
DECLARE @makeId53 uniqueidentifier; SELECT @makeId53 = Id FROM dbo.VehicleMakes WHERE Name = 'Hyundai'; IF @makeId53 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId53 AND Name = 'Sonata') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId53, 'Sonata', 1989, NULL, 1);
DECLARE @makeId54 uniqueidentifier; SELECT @makeId54 = Id FROM dbo.VehicleMakes WHERE Name = 'Hyundai'; IF @makeId54 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId54 AND Name = 'Tucson') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId54, 'Tucson', 2005, NULL, 1);
DECLARE @makeId55 uniqueidentifier; SELECT @makeId55 = Id FROM dbo.VehicleMakes WHERE Name = 'Jeep'; IF @makeId55 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId55 AND Name = 'Cherokee') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId55, 'Cherokee', 1974, NULL, 1);
DECLARE @makeId56 uniqueidentifier; SELECT @makeId56 = Id FROM dbo.VehicleMakes WHERE Name = 'Jeep'; IF @makeId56 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId56 AND Name = 'Compass') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId56, 'Compass', 2007, NULL, 1);
DECLARE @makeId57 uniqueidentifier; SELECT @makeId57 = Id FROM dbo.VehicleMakes WHERE Name = 'Jeep'; IF @makeId57 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId57 AND Name = 'Grand Cherokee') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId57, 'Grand Cherokee', 1993, NULL, 1);
DECLARE @makeId58 uniqueidentifier; SELECT @makeId58 = Id FROM dbo.VehicleMakes WHERE Name = 'Jeep'; IF @makeId58 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId58 AND Name = 'Wrangler') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId58, 'Wrangler', 1987, NULL, 1);
DECLARE @makeId59 uniqueidentifier; SELECT @makeId59 = Id FROM dbo.VehicleMakes WHERE Name = 'Kia'; IF @makeId59 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId59 AND Name = 'Forte') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId59, 'Forte', 2010, NULL, 1);
DECLARE @makeId60 uniqueidentifier; SELECT @makeId60 = Id FROM dbo.VehicleMakes WHERE Name = 'Kia'; IF @makeId60 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId60 AND Name = 'Optima') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId60, 'Optima', 2001, 2020, 1);
DECLARE @makeId61 uniqueidentifier; SELECT @makeId61 = Id FROM dbo.VehicleMakes WHERE Name = 'Kia'; IF @makeId61 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId61 AND Name = 'Sorento') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId61, 'Sorento', 2003, NULL, 1);
DECLARE @makeId62 uniqueidentifier; SELECT @makeId62 = Id FROM dbo.VehicleMakes WHERE Name = 'Kia'; IF @makeId62 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId62 AND Name = 'Soul') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId62, 'Soul', 2010, NULL, 1);
DECLARE @makeId63 uniqueidentifier; SELECT @makeId63 = Id FROM dbo.VehicleMakes WHERE Name = 'Kia'; IF @makeId63 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId63 AND Name = 'Sportage') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId63, 'Sportage', 1995, NULL, 1);
DECLARE @makeId64 uniqueidentifier; SELECT @makeId64 = Id FROM dbo.VehicleMakes WHERE Name = 'Lexus'; IF @makeId64 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId64 AND Name = 'ES') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId64, 'ES', 1990, NULL, 1);
DECLARE @makeId65 uniqueidentifier; SELECT @makeId65 = Id FROM dbo.VehicleMakes WHERE Name = 'Lexus'; IF @makeId65 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId65 AND Name = 'IS') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId65, 'IS', 2001, NULL, 1);
DECLARE @makeId66 uniqueidentifier; SELECT @makeId66 = Id FROM dbo.VehicleMakes WHERE Name = 'Lexus'; IF @makeId66 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId66 AND Name = 'RX') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId66, 'RX', 1999, NULL, 1);
DECLARE @makeId67 uniqueidentifier; SELECT @makeId67 = Id FROM dbo.VehicleMakes WHERE Name = 'Lexus'; IF @makeId67 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId67 AND Name = 'NX') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId67, 'NX', 2015, NULL, 1);
DECLARE @makeId68 uniqueidentifier; SELECT @makeId68 = Id FROM dbo.VehicleMakes WHERE Name = 'Lincoln'; IF @makeId68 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId68 AND Name = 'MKZ') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId68, 'MKZ', 2007, 2020, 1);
DECLARE @makeId69 uniqueidentifier; SELECT @makeId69 = Id FROM dbo.VehicleMakes WHERE Name = 'Lincoln'; IF @makeId69 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId69 AND Name = 'Navigator') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId69, 'Navigator', 1998, NULL, 1);
DECLARE @makeId70 uniqueidentifier; SELECT @makeId70 = Id FROM dbo.VehicleMakes WHERE Name = 'Lincoln'; IF @makeId70 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId70 AND Name = 'Aviator') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId70, 'Aviator', 2003, NULL, 1);
DECLARE @makeId71 uniqueidentifier; SELECT @makeId71 = Id FROM dbo.VehicleMakes WHERE Name = 'Lincoln'; IF @makeId71 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId71 AND Name = 'Corsair') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId71, 'Corsair', 2020, NULL, 1);
DECLARE @makeId72 uniqueidentifier; SELECT @makeId72 = Id FROM dbo.VehicleMakes WHERE Name = 'Mazda'; IF @makeId72 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId72 AND Name = 'CX-5') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId72, 'CX-5', 2013, NULL, 1);
DECLARE @makeId73 uniqueidentifier; SELECT @makeId73 = Id FROM dbo.VehicleMakes WHERE Name = 'Mazda'; IF @makeId73 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId73 AND Name = 'CX-9') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId73, 'CX-9', 2007, NULL, 1);
DECLARE @makeId74 uniqueidentifier; SELECT @makeId74 = Id FROM dbo.VehicleMakes WHERE Name = 'Mazda'; IF @makeId74 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId74 AND Name = 'Mazda3') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId74, 'Mazda3', 2004, NULL, 1);
DECLARE @makeId75 uniqueidentifier; SELECT @makeId75 = Id FROM dbo.VehicleMakes WHERE Name = 'Mazda'; IF @makeId75 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId75 AND Name = 'Mazda6') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId75, 'Mazda6', 2003, 2021, 1);
DECLARE @makeId76 uniqueidentifier; SELECT @makeId76 = Id FROM dbo.VehicleMakes WHERE Name = 'Mercedes-Benz'; IF @makeId76 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId76 AND Name = 'C-Class') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId76, 'C-Class', 1994, NULL, 1);
DECLARE @makeId77 uniqueidentifier; SELECT @makeId77 = Id FROM dbo.VehicleMakes WHERE Name = 'Mercedes-Benz'; IF @makeId77 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId77 AND Name = 'E-Class') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId77, 'E-Class', 1994, NULL, 1);
DECLARE @makeId78 uniqueidentifier; SELECT @makeId78 = Id FROM dbo.VehicleMakes WHERE Name = 'Mercedes-Benz'; IF @makeId78 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId78 AND Name = 'GLC') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId78, 'GLC', 2016, NULL, 1);
DECLARE @makeId79 uniqueidentifier; SELECT @makeId79 = Id FROM dbo.VehicleMakes WHERE Name = 'Mercedes-Benz'; IF @makeId79 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId79 AND Name = 'GLE') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId79, 'GLE', 2016, NULL, 1);
DECLARE @makeId80 uniqueidentifier; SELECT @makeId80 = Id FROM dbo.VehicleMakes WHERE Name = 'Nissan'; IF @makeId80 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId80 AND Name = 'Altima') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId80, 'Altima', 1993, NULL, 1);
DECLARE @makeId81 uniqueidentifier; SELECT @makeId81 = Id FROM dbo.VehicleMakes WHERE Name = 'Nissan'; IF @makeId81 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId81 AND Name = 'Frontier') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId81, 'Frontier', 1998, NULL, 1);
DECLARE @makeId82 uniqueidentifier; SELECT @makeId82 = Id FROM dbo.VehicleMakes WHERE Name = 'Nissan'; IF @makeId82 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId82 AND Name = 'Rogue') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId82, 'Rogue', 2008, NULL, 1);
DECLARE @makeId83 uniqueidentifier; SELECT @makeId83 = Id FROM dbo.VehicleMakes WHERE Name = 'Nissan'; IF @makeId83 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId83 AND Name = 'Sentra') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId83, 'Sentra', 1982, NULL, 1);
DECLARE @makeId84 uniqueidentifier; SELECT @makeId84 = Id FROM dbo.VehicleMakes WHERE Name = 'Nissan'; IF @makeId84 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId84 AND Name = 'Titan') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId84, 'Titan', 2004, NULL, 1);
DECLARE @makeId85 uniqueidentifier; SELECT @makeId85 = Id FROM dbo.VehicleMakes WHERE Name = 'Ram'; IF @makeId85 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId85 AND Name = '1500') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId85, '1500', 2011, NULL, 1);
DECLARE @makeId86 uniqueidentifier; SELECT @makeId86 = Id FROM dbo.VehicleMakes WHERE Name = 'Ram'; IF @makeId86 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId86 AND Name = '2500') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId86, '2500', 2011, NULL, 1);
DECLARE @makeId87 uniqueidentifier; SELECT @makeId87 = Id FROM dbo.VehicleMakes WHERE Name = 'Ram'; IF @makeId87 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId87 AND Name = '3500') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId87, '3500', 2011, NULL, 1);
DECLARE @makeId88 uniqueidentifier; SELECT @makeId88 = Id FROM dbo.VehicleMakes WHERE Name = 'Ram'; IF @makeId88 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId88 AND Name = 'ProMaster') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId88, 'ProMaster', 2014, NULL, 1);
DECLARE @makeId89 uniqueidentifier; SELECT @makeId89 = Id FROM dbo.VehicleMakes WHERE Name = 'Subaru'; IF @makeId89 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId89 AND Name = 'Forester') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId89, 'Forester', 1998, NULL, 1);
DECLARE @makeId90 uniqueidentifier; SELECT @makeId90 = Id FROM dbo.VehicleMakes WHERE Name = 'Subaru'; IF @makeId90 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId90 AND Name = 'Impreza') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId90, 'Impreza', 1993, NULL, 1);
DECLARE @makeId91 uniqueidentifier; SELECT @makeId91 = Id FROM dbo.VehicleMakes WHERE Name = 'Subaru'; IF @makeId91 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId91 AND Name = 'Outback') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId91, 'Outback', 1995, NULL, 1);
DECLARE @makeId92 uniqueidentifier; SELECT @makeId92 = Id FROM dbo.VehicleMakes WHERE Name = 'Subaru'; IF @makeId92 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId92 AND Name = 'Crosstrek') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId92, 'Crosstrek', 2013, NULL, 1);
DECLARE @makeId93 uniqueidentifier; SELECT @makeId93 = Id FROM dbo.VehicleMakes WHERE Name = 'Toyota'; IF @makeId93 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId93 AND Name = 'Camry') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId93, 'Camry', 1983, NULL, 1);
DECLARE @makeId94 uniqueidentifier; SELECT @makeId94 = Id FROM dbo.VehicleMakes WHERE Name = 'Toyota'; IF @makeId94 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId94 AND Name = 'Corolla') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId94, 'Corolla', 1970, NULL, 1);
DECLARE @makeId95 uniqueidentifier; SELECT @makeId95 = Id FROM dbo.VehicleMakes WHERE Name = 'Toyota'; IF @makeId95 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId95 AND Name = 'Highlander') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId95, 'Highlander', 2001, NULL, 1);
DECLARE @makeId96 uniqueidentifier; SELECT @makeId96 = Id FROM dbo.VehicleMakes WHERE Name = 'Toyota'; IF @makeId96 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId96 AND Name = 'RAV4') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId96, 'RAV4', 1996, NULL, 1);
DECLARE @makeId97 uniqueidentifier; SELECT @makeId97 = Id FROM dbo.VehicleMakes WHERE Name = 'Toyota'; IF @makeId97 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId97 AND Name = 'Tacoma') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId97, 'Tacoma', 1995, NULL, 1);
DECLARE @makeId98 uniqueidentifier; SELECT @makeId98 = Id FROM dbo.VehicleMakes WHERE Name = 'Toyota'; IF @makeId98 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId98 AND Name = 'Tundra') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId98, 'Tundra', 2000, NULL, 1);
DECLARE @makeId99 uniqueidentifier; SELECT @makeId99 = Id FROM dbo.VehicleMakes WHERE Name = 'Volkswagen'; IF @makeId99 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId99 AND Name = 'Atlas') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId99, 'Atlas', 2018, NULL, 1);
DECLARE @makeId100 uniqueidentifier; SELECT @makeId100 = Id FROM dbo.VehicleMakes WHERE Name = 'Volkswagen'; IF @makeId100 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId100 AND Name = 'Golf') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId100, 'Golf', 1975, NULL, 1);
DECLARE @makeId101 uniqueidentifier; SELECT @makeId101 = Id FROM dbo.VehicleMakes WHERE Name = 'Volkswagen'; IF @makeId101 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId101 AND Name = 'Jetta') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId101, 'Jetta', 1980, NULL, 1);
DECLARE @makeId102 uniqueidentifier; SELECT @makeId102 = Id FROM dbo.VehicleMakes WHERE Name = 'Volkswagen'; IF @makeId102 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId102 AND Name = 'Passat') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId102, 'Passat', 1990, 2022, 1);
DECLARE @makeId103 uniqueidentifier; SELECT @makeId103 = Id FROM dbo.VehicleMakes WHERE Name = 'Volkswagen'; IF @makeId103 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId103 AND Name = 'Tiguan') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId103, 'Tiguan', 2009, NULL, 1);
DECLARE @makeId104 uniqueidentifier; SELECT @makeId104 = Id FROM dbo.VehicleMakes WHERE Name = 'Volvo'; IF @makeId104 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId104 AND Name = 'S60') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId104, 'S60', 2001, NULL, 1);
DECLARE @makeId105 uniqueidentifier; SELECT @makeId105 = Id FROM dbo.VehicleMakes WHERE Name = 'Volvo'; IF @makeId105 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId105 AND Name = 'S80') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId105, 'S80', 1999, 2016, 1);
DECLARE @makeId106 uniqueidentifier; SELECT @makeId106 = Id FROM dbo.VehicleMakes WHERE Name = 'Volvo'; IF @makeId106 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId106 AND Name = 'XC60') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId106, 'XC60', 2010, NULL, 1);
DECLARE @makeId107 uniqueidentifier; SELECT @makeId107 = Id FROM dbo.VehicleMakes WHERE Name = 'Volvo'; IF @makeId107 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.VehicleModels WHERE VehicleMakeId = @makeId107 AND Name = 'XC90') INSERT INTO dbo.VehicleModels (Id, VehicleMakeId, Name, StartYear, EndYear, IsActive) VALUES (NEWID(), @makeId107, 'XC90', 2003, NULL, 1);
");
    }

    protected override void Down(MigrationBuilder migrationBuilder) => throw new NotSupportedException("RefactorServiceRequestDomain is a data-copy migration and is not safely reversible.");
}
