using System.ComponentModel.DataAnnotations;

namespace SecondShiftAutoCare.Shared.Models;

public static class PaymentStatuses { public const string NotPaid="NotPaid"; public const string PartiallyPaid="PartiallyPaid"; public const string Paid="Paid"; public const string Waived="Waived"; public static readonly string[] All=[NotPaid,PartiallyPaid,Paid,Waived]; }
public static class PaymentMethods { public const string Cash="Cash"; public const string Venmo="Venmo"; public const string PayPal="PayPal"; public const string Check="Check"; public const string Other="Other"; public static readonly string[] All=[Cash,Venmo,PayPal,Check,Other]; }
public static class ServiceLocationTypes { public const string MyGarage="MyGarage"; public const string CustomerDriveway="CustomerDriveway"; public const string TBD="TBD"; public static readonly string[] All=[MyGarage,CustomerDriveway,TBD]; }
public static class RiskRecommendations { public const string GoodFit="GoodFit"; public const string Maybe="Maybe"; public const string DeclineOrReferOut="DeclineOrReferOut"; public static readonly string[] All=[GoodFit,Maybe,DeclineOrReferOut]; }
public static class IntakeAnswerTypes { public const string Text="Text"; public const string YesNo="YesNo"; public const string Choice="Choice"; public static readonly string[] All=[Text,YesNo,Choice]; }

public sealed class ServiceIntakeQuestionDto { public Guid Id { get; set; } public string ServiceType { get; set; }=string.Empty; public string QuestionText { get; set; }=string.Empty; public string? HelpText { get; set; } public string AnswerType { get; set; }=IntakeAnswerTypes.Text; public string? OptionsJson { get; set; } public bool IsRequired { get; set; } public int SortOrder { get; set; } }
public sealed class ServiceIntakeAnswerDto { public Guid? QuestionId { get; set; } public string QuestionText { get; set; }=string.Empty; public string? AnswerText { get; set; } }
public sealed class JobChecklistItemDto { public Guid Id { get; set; } public string Text { get; set; }=string.Empty; public bool IsCompleted { get; set; } public DateTime? CompletedUtc { get; set; } public int SortOrder { get; set; } public bool IsCustom { get; set; } }
public sealed class ChecklistItemUpdateModel { public bool IsCompleted { get; set; } }
public sealed class ChecklistItemCreateModel { [Required, StringLength(300)] public string Text { get; set; }=string.Empty; }
public sealed class ServiceRequestScheduleUpdateModel { public DateTime? ScheduledStartUtc { get; set; } public DateTime? ScheduledEndUtc { get; set; } [Range(0,10000)] public int? EstimatedDurationMinutes { get; set; } [StringLength(50)] public string? ServiceLocationType { get; set; } [StringLength(1000)] public string? ScheduleNotes { get; set; } }
public sealed class PaymentDto { public string PaymentStatus { get; set; }=PaymentStatuses.NotPaid; public string? PaymentMethod { get; set; } public decimal? AmountDue { get; set; } public decimal? AmountPaid { get; set; } public DateTime? PaidUtc { get; set; } public string? Notes { get; set; } }
public sealed class JobRiskAssessmentDto { public bool RustConcern { get; set; } public bool RequiresLift { get; set; } public bool CustomerSuppliedParts { get; set; } public bool KnownDifficultVehicle { get; set; } public decimal? EstimatedHours { get; set; } public bool SafetyCritical { get; set; } public bool NeedsAlignment { get; set; } public bool NeedsTow { get; set; } public bool MobileWorkConcern { get; set; } public int RiskScore { get; set; } public string Recommendation { get; set; }=RiskRecommendations.GoodFit; public string? Notes { get; set; } }
public sealed class PublicRequestStatusDto { public string BusinessName { get; set; }="2nd Shift Auto Care"; public string Status { get; set; }=string.Empty; public string Vehicle { get; set; }=string.Empty; public string ServiceType { get; set; }=string.Empty; public DateTime SubmittedUtc { get; set; } public DateTime? ScheduledStartUtc { get; set; } public DateTime? ScheduledEndUtc { get; set; } public decimal? EstimateLow { get; set; } public decimal? EstimateHigh { get; set; } public decimal? TotalEstimate { get; set; } public string CustomerApprovalStatus { get; set; }=ServiceRequestApprovalStatuses.Pending; public string NextStepMessage { get; set; }=string.Empty; }
public sealed class PublicQuoteDto { public string Vehicle { get; set; }=string.Empty; public string ServiceType { get; set; }=string.Empty; public decimal? EstimateLow { get; set; } public decimal? EstimateHigh { get; set; } public decimal? TotalEstimate { get; set; } public string? GoodOption { get; set; } public string? BetterOption { get; set; } public string? BestOption { get; set; } public string? AssumptionDisclaimerText { get; set; } public string? PartsNeeded { get; set; } public DateTime? ScheduledStartUtc { get; set; } public DateTime? ScheduledEndUtc { get; set; } public string CustomerApprovalStatus { get; set; }=ServiceRequestApprovalStatuses.Pending; public string? CustomerApprovalMessage { get; set; } }
public sealed class QuoteDecisionModel { [Required] public string Decision { get; set; }=ServiceRequestApprovalStatuses.Approved; [StringLength(2000)] public string? Message { get; set; } }
public sealed class CustomerHistoryDto { public Guid Id { get; set; } public string Name { get; set; }=string.Empty; public string Phone { get; set; }=string.Empty; public string? Email { get; set; } public List<ServiceRequestDto> Requests { get; set; }=[]; public List<VehicleSummaryDto> Vehicles { get; set; }=[]; public int CompletedJobs { get; set; } public int OpenJobs { get; set; } public decimal TotalEstimatedRevenue { get; set; } public decimal TotalPaidAmount { get; set; } public DateTime? LastServiceDate { get; set; } }
public sealed class VehicleHistoryDto { public Guid Id { get; set; } public Guid? CustomerId { get; set; } public string CustomerName { get; set; }=string.Empty; public int Year { get; set; } public string Make { get; set; }=string.Empty; public string Model { get; set; }=string.Empty; public int? Mileage { get; set; } public List<ServiceRequestDto> Requests { get; set; }=[]; public DateTime? LastOilChange { get; set; } public DateTime? LastBrakeJob { get; set; } public List<string> KnownIssues { get; set; }=[]; public List<string> PartsHistory { get; set; }=[]; }
public sealed class VehicleSummaryDto { public Guid Id { get; set; } public int Year { get; set; } public string Make { get; set; }=string.Empty; public string Model { get; set; }=string.Empty; public int? Mileage { get; set; } }
